### ISSUE TITLE
CrashLoopBackOff - when deploying with the arg: 'enablePreviewPolicies: true'

### ISSUE THREAD

**Issue by dfs5** [nginxinc/nginx-ingress-operator#110]
**Describe the bug**
When I try to change the default: 'enablePreviewPolicies: false' to 'enablePreviewPolicies: true' container crashes with error log:
I0515 04:04:05.527868       1 verify.go:72] Unable to fetch version: error getting client: Get "http://config-version/configVersion": dial unix /var/lib/nginx/nginx-config-version.sock: connect: no such file or directory
I0515 04:04:05.528026       1 verify.go:72] Unable to fetch version: error getting client: Get "http://config-version/configVersion": dial unix /var/lib/nginx/nginx-config-version.sock: connect: no such file or directory
I0515 04:04:05.528184       1 verify.go:72] Unable to fetch version: error getting client: Get "http://config-version/configVersion": dial unix /var/lib/nginx/nginx-config-version.sock: connect: no such file or directory
I0515 04:04:05.528356       1 verify.go:72] Unable to fetch version: error getting client: Get "http://config-version/configVersion": dial unix /var/lib/nginx/nginx-config-version.sock: connect: no such file or directory
F0515 04:04:05.528434       1 manager.go:284] Could not get newest config version: could not get expected version: 0 after 4s

**To Reproduce**
1. Deploy:

apiVersion: k8s.nginx.org/v1alpha1
kind: NginxIngressController
metadata:
  name: my-nginx-ingress-controller
  namespace: nginx-ingress
spec:
  logLevel: 3
  wildcardTLS: ''
  enableCRDs: true
  ingressClass: nginx
  enableLeaderElection: false
  enableLatencyMetrics: false
  nginxStatus:
    allowCidrs: 127.0.0.1
    enable: true
    port: 9090
  watchNamespace: ''
  nginxReloadTimeout: 0
  healthStatus:
    enable: true
    uri: ''
  appProtect:
    enable: false
  serviceType: NodePort
  defaultSecret: ''
  globalConfiguration: ''
  nginxPlus: true
  enablePreviewPolicies: false
  service: null
  useIngressClassOnly: true
  enableSnippets: false
  nginxDebug: false
  type: deployment
  image:
    pullPolicy: Always
    repository: >-
      some-private-registry/nginx-ingress/openshift-image-plus
    tag: 1.11.1
  replicas: null
  enableTLSPassthrough: true
status:
  deployed: true

2. Pod should start without issues
3. Change yaml to 'enablePreviewPolicies: true'  <-- here is the issue!!!
4. View Pod staus and logs in OpenShift admin webconsole.

**Expected behavior**
Pos should start with a new configuration.

**Your environment**
* Version of the NGINX Ingress Operator: 0.1.1
* Version of the Ingress Controller: NGINX Plus 1.11.1
* Version of Kubernetes: OpenShift Container Platform 4.7.8
* Using NGINX or NGINX Plus: Plus

**Additional context**
I am running my OCP as a mini cluster 'Red Hat CodeReady Containers'  on a MAC book.

**Comment by ciarams87** [comment]
Hi @dfs5 
Sorry for the delayed reply.

I couldn't replicate this in my environment (OpenShift 4.7 running on AWS, v0.3.0 of the Operator, NIC v1.12.0), but I notice that in your description you are using NGINX Plus 1.11.1 but your Operator version is  0.1.0.

We have a 1-2-1 relationship between Operator and IC versions, and v0.1.0 of Operator is only compatible with v1.10.x of the IC. See https://github.com/nginxinc/nginx-ingress-operator#nginx-ingress-operator for the full table.

Thanks,
Ciara
