### ISSUE TITLE
Customize Annotations on the Generated Service

### ISSUE THREAD

**Issue by jshure** [nginxinc/nginx-ingress-operator#114]
**Is your feature request related to a problem? Please describe.**

This seems so basic, I feel like I must be missing something.  Apologies in advance if this is the case.  

It it doesn't appear possible to add custom annotations onto the service generated by the operator.  With the service field I can add labels to the service (NginxIngressController.Service extraLabels), but this appears to be the only customization available.

https://github.com/nginxinc/nginx-ingress-operator/blob/765947b594b85e83a209e8b1bd2e0ee715215845/pkg/controller/nginxingresscontroller/service.go#L12

I cannot, therefore, add custom annotations to do things like create an internal AWS LB : service.beta.kubernetes.io/aws-load-balancer-internal: "true"

Without custom annotations the generated service is not usable for us (and I am surprised it is not unusable for many usecases).  

**Describe the solution you'd like**

Similar to custom labels, allow custom annotations.

Alternatively, disable service generation when a field indicates a custom service should be used.

**Describe alternatives you've considered**

The only workaround I have found is first creating a service with the same name as the controller.  In this case the operator does not overwrite the existing service.  I'm not sure I trust this as a solution.

**Comment by pleshakov** [comment]
Hi @jshure 

> Similar to custom labels, allow custom annotations.

sounds reasonable. we might have it soon from https://github.com/nginxinc/nginx-ingress-operator/pull/102 

>  Alternatively, disable service generation when a field indicates a custom service should be used.

this makes sense even after the first enhancement is implemented, for allowing using a custom service.

> The only workaround I have found is first creating a service with the same name as the controller. In this case the operator does not overwrite the existing service. I'm not sure I trust this as a solution.

another approach is to configure `serviceType: NodePort`, which will make the Operator create a nodeport service, not the LoadBalancer. And create a custom LoadBalancer service using the same selector.

**Comment by rotty3000** [comment]
Was this issue ultimately resolved behind the scenes or could we reopen? This is important for us.

**Comment by rotty3000** [comment]
hey, never mind! ;) I think this is done here https://github.com/nginxinc/nginx-ingress-operator/blob/v0.5.0/controllers/service.go#L18
