### ISSUE TITLE
Operator Manual Installation Files Don't Exist

### ISSUE THREAD

**Issue by mtyazici** [nginxinc/nginx-ingress-operator#122]
**Describe the bug**
There are files used to deploy operator in the documentation at https://github.com/nginxinc/nginx-ingress-operator/blob/master/docs/manual-installation.md. However, those files do not exist under this repository. I assume they were deleted at some point. Could you update the documentation?

**Comment by jasonwilliams14** [comment]
Hi @mtyazici 
Thank you for contacting us. I will work with the team to update are documents to be more precise. Thank you for your input.

In the meantime, here is the direct link to the files you are looking for:

[NGINX operator install files](https://github.com/nginxinc/nginx-ingress-operator/tree/release-0.2.0/deploy)

Let us know if that helps.
Cheers

**Comment by ciarams87** [comment]
Hi @mtyazici 

Sorry about the confusion - we re-organised the repo during this last release and there was a bit of delay with updating the docs in master. 

The documentation has since been updated in master and in v0.3.0.

Thanks,
Ciara
