### ISSUE TITLE
exposing TCP service using nginx ingress controller operator on openshift

### ISSUE THREAD

**Issue by vknemanavar** [nginxinc/nginx-ingress-operator#123]
We are trying to expose TCP service and trying to follow below document.

https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/

But flag --tcp-services-configmap unable to add it do deployment either nginx ingress controller, when I add it to deployment it is not persisting because deployment is controlled by nginx ingress controller operator. I am not finding option to add flag --tcp-services-configmap in nginx ingress controller, is there any other way I can add this flag to nginx ingress controller? Or any other way to expose TCP service using nginx ingress controller which is installed using operator.

**Comment by jasonwilliams14** [comment]
Hi @vknemanavar 
That particular document that you linked is to a different NGINX Ingress controller that is maintained by the community. Those settings will not apply to `nginxinc` Ingress controller.   

That said, sounds like what you are looking for is `Transport server` feature that we do support in this product.
Take a look at this link to learn more on `Transport server`:

[NGINX Ingress Transport Server](https://docs.nginx.com/nginx-ingress-controller/configuration/transportserver-resource/)

Let us know if that helps.

**Comment by vknemanavar** [comment]
Using transportserver resource exposing app over TCP it worked, this issue can be closed.
