### ISSUE TITLE
Example given is not working

### ISSUE THREAD

**Issue by Ronanb3** [nginxinc/nginx-ingress-operator#128]
Hi,
I installed the operator successfully, then I added the example but the secret file is not available.

```
$ oc logs my-nginx-ingress-controller-c897bf869-f5bv5
I0705 10:33:03.781234       1 main.go:271] Starting NGINX Ingress controller Version=v1.11.1-SNAPSHOT-5f68a361 GitCommit=5f68a361cd4a5adb49458c3c25bc00bac19545b2 Date=2021-07-02T13:07:53Z PlusFlag=false
W0705 10:33:03.798103       1 main.go:310] The '-use-ingress-class-only' flag will be deprecated and has no effect on versions of kubernetes >= 1.18.0. Processing ONLY resources that have the 'ingressClassName' field in Ingress equal to the class.
W0705 10:33:03.805773       1 warnings.go:70] networking.k8s.io/v1beta1 IngressClass is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 IngressClassList
I0705 10:33:03.812987       1 main.go:413] Using nginx version: nginx/1.21.0
F0705 10:33:03.823170       1 main.go:447] Error trying to get the default server TLS secret nginx-ingress/default-server-secret: could not get nginx-ingress/default-server-secret: secrets "default-server-secret" not found
```

How to get the secret files?

**Comment by ciarams87** [comment]
Hi @Ronanb3 

Sorry for the delay in getting back to you.

If the default secret parameter is set, it needs to be created in the cluster first. See https://github.com/nginxinc/kubernetes-ingress/blob/master/deployments/common/default-server-secret.yaml for an example default secret configuration. 

Could you please confirm the exact configuration you used to deploy the ingress controller? The  example we have in our documentation is the minimum install, and doesn't set the `defaultSecret`. I am guessing you might have taken the full example listing all fields from [here](https://github.com/nginxinc/nginx-ingress-operator/blob/master/docs/nginx-ingress-controller.md#configuration)? Instead, you can try using the example [here](https://github.com/nginxinc/nginx-ingress-operator/tree/master/examples/deployment-oss-min).

The [full configuration example](https://github.com/nginxinc/nginx-ingress-operator/blob/master/docs/nginx-ingress-controller.md#configuration) also includes descriptions of all the fields.

Thanks,
Ciara
