### ISSUE TITLE
Specify loadBalancerIP for service type of LoadBalancer

### ISSUE THREAD

**Issue by jakuboskera** [nginxinc/nginx-ingress-operator#146]
Currently there is no option how to set static IP address for service type of LoadBalancer of nginx ingress instance via nginx-ingress-operator.

Helm chart for [nginxinc/kubernetes-ingress](https://github.com/nginxinc/kubernetes-ingress/tree/v1.12.0/deployments/helm-chart) has this option `controller.service.loadBalancerIP` which set the external static IP for service.

Is there any plan to implement this feature?

**Comment by leandroaguiar-lr** [comment]
I'm in need of this feature as well.
I'm trying to have the ingress controller use a pre-allocated static IP from my cloud provider and without this I have to create another Service with the `LoadBalancer` type to be able to set the field, which means the built-in Service is unused.

As a matter of fact, other Service fields could be exposed as well, like `.spec.service.externalTrafficPolicy` and `spec.service.clusterIP` (if `ClusterIP` is allowed as a Service type).

**Comment by lucacome** [comment]
This project has moved to https://github.com/nginxinc/nginx-ingress-helm-operator
If this is still an issue, please report it again in that repo.
Thanks!
