### ISSUE TITLE
Operator installation

### ISSUE THREAD

**Issue by TheHunter** [nginxinc/nginx-ingress-operator#160]
Hi everyone,
honestly I don't understand how this operator could be installed manually.

In the documentation is specified to execute this command:

 make deploy IMG=nginx/nginx-ingress-operator:0.3.0

After cloning the repo, but why? 

Is it possible to install this operator in a simplest way?, I mean:
- execute all yaml manifest (inside a directory) which contains all ones for all CRDs

Sorry for this question, but about "make deploy" command.. what is it? I don't know it.

Thanks in advance.

**Comment by nic-hima** [comment]
Hi @TheHunter , I understand how this could be confusing! 

The simple answer is, `make deploy` runs `kustomize build` & pipes the output to a `kubectl apply`.  The `IMG=` in your command is used to set the image of the operator to run. See: https://github.com/nginxinc/nginx-ingress-operator/blob/405aebaa6928ef19ebea6c2794ba0b7d197bbab8/Makefile#L124-L126 

Kustomize if you are unfamiliar with it is a way to manage yaml manifests (a distant cousin of helm). If you'd like to look more into it, see: https://www.densify.com/kubernetes-tools/kustomize
