### ISSUE TITLE
Additional containers and volumes

### ISSUE THREAD

**Issue by sagikazarmark** [nginxinc/nginx-ingress-operator#174]
**Is your feature request related to a problem? Please describe.**
I'd like to run custom Lua scripts that require an additional side car container and some volume mounts for configuration.

**Describe the solution you'd like**
Add support for extra containers and volumes/volumeMounts in the spec.

**Describe alternatives you've considered**
The alternative is building an image that runs the sidecar binary in itself, but that's not a good practice.

Another alternative is using mutating webhooks, but that requires something like #185 as well.

**Comment by sagikazarmark** [comment]
Any thoughts? I'd be happy to work on the necessary changes.

**Comment by lucacome** [comment]
This project has moved to https://github.com/nginxinc/nginx-ingress-helm-operator
If this is still an issue, please report it again in that repo.
Thanks!
