### ISSUE TITLE
URGENT: missing webhook & cert-manager dirs & other deploy errors

### ISSUE THREAD

**Issue by nic-hima** [nginxinc/nginx-ingress-operator#183]
**Describe the bug**
While attempting to deploy this operator locally & enable `webhook` and `cert-manager` following the comments in https://github.com/nginxinc/nginx-ingress-operator/blob/master/config/default/kustomization.yaml I noticed:
- some folders & files are missing under `config` directory 
  - `/webhook` and `/cert-manager` dirs
  -  files `webhookcainjection_patch.yaml` & `manager_webhook_patch.yaml`
- some missing values in `config/crd/patches/webhook_in_nginxingresscontrollers.yaml`
- deploying vanilla on local `kind` cluster results in imagePullBackoff of image `registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.7`

**To Reproduce**
- Assuming the repo has been cloned locally

5 separate errors found so far:

**Bug1** Steps to reproduce the behavior - `../webhook not found` when trying to deploy with `webhook` enabled:
1. Uncomment https://github.com/nginxinc/nginx-ingress-operator/blob/master/config/default/kustomization.yaml#L21
2. run `make deploy`, view error logs:
```
<some non-important logs>....
Error: accumulating resources: 2 errors occurred:
        * accumulateFile error: "accumulating resources from '../webhook': evalsymlink failure on '<localpath-to-repo>/nginx-ingress-operator/config/webhook' : lstat <localpath-to-repo>/nginx-ingress-operator/config/webhook: no such file or directory"
        * loader.New error: "error loading ../webhook with git: url lacks host: ../webhook, dir: evalsymlink failure on '<localpath-to-repo>/nginx-ingress-operator/config/webhook' : lstat <localpath-to-repo>/nginx-ingress-operator/config/webhook: no such file or directory, get: invalid source string: ../webhook"
```
---

**Bug2** Steps to reproduce the behavior - `../cert-manager not found` when trying to deploy with `cert-manager` enabled:
1. Following the comments, uncomment line https://github.com/nginxinc/nginx-ingress-operator/blob/master/config/default/kustomization.yaml#L23
2. run `make deploy`, view error logs:
```
<some non-important logs>....
Error: accumulating resources: 2 errors occurred:
        * accumulateFile error: "accumulating resources from '../certmanager': evalsymlink failure on '/<localpath-to-repo>/nginx-ingress-operator/config/certmanager' : lstat <localpath-to-repo>/nginx-ingress-operator/config/certmanager: no such file or directory"
        * loader.New error: "error loading ../certmanager with git: url lacks host: ../certmanager, dir: evalsymlink failure on '<localpath-to-repo>/nginx-ingress-operator/config/certmanager' : lstat<localpath-to-repo>/nginx-ingress-operator/config/certmanager: no such file or directory, get: invalid source string: ../certmanager"
```
---

**Bug3** Steps to reproduce the behavior - `crd definition validation failed` when trying to include conversion webhook:
1. Uncomment https://github.com/nginxinc/nginx-ingress-operator/blob/master/config/crd/kustomization.yaml#L11
2. run `make deploy`, view error logs:
```
<some non-important logs>...
error: error validating "STDIN": error validating data: ValidationError(CustomResourceDefinition.spec.conversion.webhook): missing required field "conversionReviewVersions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.WebhookConversion; if you choose to ignore these errors, turn validation off with --validate=false
make: *** [deploy] Error 1
```
---

**Bug4** Steps to reproduce the behavior - `webhookcainjection_patch.yaml` & `manager_webhook_patch.yaml` files not found when trying to deploy with both `webhook` and `cert-manager` enabled:
1. Following comments, uncomment lines https://github.com/nginxinc/nginx-ingress-operator/blob/405aebaa6928ef19ebea6c2794ba0b7d197bbab8/config/default/kustomization.yaml#L39 & https://github.com/nginxinc/nginx-ingress-operator/blob/405aebaa6928ef19ebea6c2794ba0b7d197bbab8/config/default/kustomization.yaml#L44
2. Run `make deploy`, view error logs below:
Below is error for `manager_webhook_patch.yaml`
```
<some non-important logs>...
- manager_webhook_patch.yaml
`: evalsymlink failure on '<localpath-to-repo>/nginx-ingress-operator/config/default/manager_webhook_patch.yaml' : lstat <localpath-to-repo>/nginx-ingress-operator/config/default/manager_webhook_patch.yaml: no such file or directory
error: no objects passed to apply
make: *** [deploy] Error 1
```

Below is error for `webhookcainjection_patch.yaml`
```
- webhookcainjection_patch.yaml
`: evalsymlink failure on '<localpath-to-repo>/nginx-ingress-operator/config/default/webhookcainjection_patch.yaml' : lstat <localpath-to-repo>/nginx-ingress-operator/config/default/webhookcainjection_patch.yaml: no such file or directory
error: no objects passed to apply
make: *** [deploy] Error 1
```
---

**Bug5** Steps to reproduce the behavior - `kube-proxy image-pull backoff` on `kind` cluster:
1. Run `make deploy` without making any config changes
2. Wait for all resources to be applied, and `kubectl get pod <ingress-operator-pod-name> -oyaml` and view status:
```
status:
  conditions:
...
  containerStatuses:
  - image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.7
    imageID: ""
    lastState: {}
    name: kube-rbac-proxy
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.7"
        reason: ImagePullBackOff
  ...
```

**Expected behavior**
- As a user, deploying the vanilla operator using `make deploy` on a local cluster like `kind` should result in a non-erroring pod.
- As a user, enabling Cert-Manager & Webhook in the `/config/default/kustomization.yaml` and `config/crd/kustomization.yaml` files as noted in the coments should return a non-erroring and functional deployment.

**Your environment**
* Version of the NGINX Ingress Operator - head commit: https://github.com/nginxinc/nginx-ingress-operator/commit/405aebaa6928ef19ebea6c2794ba0b7d197bbab8
* Version of the Ingress Controller - nginx/nginx-ingress-operator:0.4.0
* Version of Kubernetes - v1.20.7
* Kubernetes platform - `kind`
* Using NGINX or NGINX Plus - Using regular NGINX

**Additional context**
It seems like the problem with `kube-proxy` is due to my local setup not being able to pull from `registry.redhat.io/openshift4/`.

**Comment by jasonwilliams14** [comment]
@nic-hima We currently do not support a webhook and cert-manager for our operator. Those were generated by the SDK, but we do not support them at this time.

For the image issue, the updated image will be in the master branch, with the updated image you will need to install with the operator.
HTH

**Comment by nic-hima** [comment]
@jasonwilliams14 Thanks for the urgency about the proxy image. 

If those extra things were generated with the SDK then I'd suggest that they be cleaned up. If I have some spare time this weekend I might throw together a PR, but regardless I hope you see how those auto-generated "extras" could be misleading to some.
