### ISSUE TITLE
Add support for --publish-status-address 

### ISSUE THREAD

**Issue by jescarri** [nginxinc/nginx-ingress-operator#28]
**Is your feature request related to a problem? Please describe.**
I would like to have a way to deploy an ingress controller that sets the 
`--publish-status-address` flag.

**Describe the solution you'd like**
Add a field in the NginxIngressController that allows this.

**Describe alternatives you've considered**
Looked at the code and seems this is not possible, I can submit a PR in the upcoming days. 

**Additional context**
I run a private ingress that uses a serviceType Loadbalancer one of the Loadbalancer service has a portForward from the internet, in combination with external-dns I can crate cname records for ingresses that I want to be exposed on the internet i/e foo.bar CNAME foo.bar.dyndns.

**Comment by pleshakov** [comment]
Hi @jescarri 

the `--publish-status-address` is a cli flag of [ingress-nginx](https://github.com/kubernetes/ingress-nginx), which is different from this project https://github.com/nginxinc/kubernetes-ingress/, which this operator supports. You can read about the differences [here](https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-ingress-controllers.md). 

At the same time, that feature is available in `nginxinc/kubernetes-ingress` and this operator. You need to set the [`external-status-address`](https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#ingress-controller-not-related-to-nginx-configuration) configmap key with the desired address (the configmap can be configured via `configMapData` field of the `NginxIngressController`) and you also need to ensure that [ReportIngressStatus.Enable](https://github.com/nginxinc/nginx-ingress-operator/blob/master/docs/nginx-ingress-controller.md#nginxingresscontrollerreportingressstatus) is set to true.

**Comment by jescarri** [comment]
@pleshakov thanks for the reply, yes I always confuse both projects hehe, I make it work, thanks for the help!.
