### ISSUE TITLE
Operator in CrashLoop after upgrade to 0.0.7

### ISSUE THREAD

**Issue by jimdaga** [nginxinc/nginx-ingress-operator#38]
**Describe the bug**
nginx-ingress-operator in `CrashLoopBackOff` after an upgrade from `nginx-ingress-operator.v0.0.6` to `nginx-ingress-operator.v0.0.7`.

Operator pod failing to start with the following error:
```
{"level":"error","ts":1608128574.0123286,"logger":"cmd","msg":"","error":"error creating KIC CRDs: error creating CustomResourceDefinition aplogconfs.appprotect.f5.com: the server could not find the requested resource","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\tcmd/manager/main.go:143\nruntime.main\n\truntime/proc.go:203"}
```

The CRD in error is  already in place from an earlier install.
```
kubectl get crd aplogconfs.appprotect.f5.com
NAME                           CREATED AT
aplogconfs.appprotect.f5.com   2020-08-04T15:57:05Z
```

It does look there there was a recent change to the CRD (hence why the operator likely is looking to update the CRD). 
I did notice the apiVersion changed:
**Installed**
```
kubectl get crd aplogconfs.appprotect.f5.com -o yaml | grep ^apiVersion
apiVersion: apiextensions.k8s.io/v1beta1
``` 
**New**
https://github.com/nginxinc/nginx-ingress-operator/blob/110be46ac0336ff22ae2c1f1d1848a9324e31c46/build/kic_crds/appprotect.f5.com_aplogconfs.yaml#L1 

I wonder if it's because Openshift 4.2.10 doesn't have`v1.apiextensions.k8s.io` yet?
```
kubectl get apiservices | grep apiextensions.k8s.io
v1beta1.apiextensions.k8s.io                Local                                                                   True                           340d
```

**To Reproduce**
_(This is for openshift 4.2.10)_
1. Install Nginx Ingress Operator v0.0.6 from the openshift OperatorHub (Not sure if there will be an issue with 0.0.7 right away, or if you need to start with 0.0.6 and upgrade to 0.0.7)
2. Upgrade to 0.0.7
3. Install Plan never finishes because the deployment never finishes its rollout (because of the CrashLoop)

**Expected behavior**
Its expected that the upgrade of the operator completes without error. 

**Your environment**
* Version of the NGINX Ingress Operator - 0.0.7 (https://github.com/nginxinc/nginx-ingress-operator/releases/tag/v0.0.7)
* Version of the Ingress Controller - 1.9.1-ubi (I think?)
* Version of Kubernetes: Openshift 4.2.10 (Based on Kubernetes 1.14)
* Kubernetes platform: Openshift
* Using NGINX or NGINX Plus: NGINX

**Additional context**
I admit; I need to upgrade my cluster. Openshift 4.6 (based on kubernetes 1.19) is out - and would probably have this API version. If that's the case, I'll have to wait till after the new year when our change freeze is over.

**Comment by lucacome** [comment]
Hi @jimdaga, 

version 0.0.7 is compatible with Openshift 4.5+ (and technically even 0.0.6 wasn't compatible with 4.2, see release notes [here](https://github.com/nginxinc/nginx-ingress-operator/releases/tag/v0.0.6))

Additionally, the Ingress Controller is verified to run on Kubernetes 1.15+ (see the doc [here](https://docs.nginx.com/nginx-ingress-controller/technical-specifications/#supported-kubernetes-versions)) so I think it's best to update to Openshift 4.6 if you can.

Let me know it makes sense or you have any other questions.

**Comment by jimdaga** [comment]
@lucacome Makes sense, thank you for helping confirm that!
