### ISSUE TITLE
Support DaemonSet configuration (nodeSelector support)

### ISSUE THREAD

**Issue by NickClark** [nginxinc/nginx-ingress-operator#40]
**Is your feature request related to a problem? Please describe.**
I would like to use the operator to deploy a DaemonSet with a `nodeSelector`.

**Describe the solution you'd like**
It would be nice if the NginxIngressController resource would allow DaemonSets to be customized

**Describe alternatives you've considered**
I'm considering modifying the DaemonSet after the Operator has deployed it, but I'm afraid it won't persist.

**Comment by frjaraur** [comment]
This will be useful even for Deployments. Is there any other placement option missed?
