### ISSUE TITLE
Unable to to access ingress hosts on more than one controller instance

### ISSUE THREAD

**Issue by NickClark** [nginxinc/nginx-ingress-operator#41]
**Describe the bug**
When deploying a DaemonSet, only one of the resulting nginx controller instances expose the Ingress resources.

**Expected behavior**
I should be able to deploy multiple replicas or daemon and be able to access all ingress resources on any of them.

**Your environment**
* Version of the NGINX Ingress Operator -  0.0.7
* Ingress Controller -1.9.1
* Kubernetes 1.18.10
* DigitalOcean
* Using NGINX 

**Additional context**
The goal here is to have at least two Nginx ingress instances scheduled to different nodes. The IP for those two nodes are provided to DNS. This provides redundancy and less downtime during upgrades. Is there a better way to accomplish this?

**Comment by NickClark** [comment]
Or perhaps, in a TLDR fashion: Is there a supported way to deploy redundant controllers? All serving the same hosts?

**Comment by pleshakov** [comment]
Hi @NickClark 

Could you possibly clarify `only one of the resulting nginx controller instances expose the Ingress resources` ? Note that the Ingress Controller replicas of a single DaemonsSet or Deployment operate independently, but shall produce the same configuration.

**Comment by NickClark** [comment]
What you describe is what I expected it to do. But it appears that it may not be getting the same config. I had two instances. I could hit port 80 on one, and get the expected response, but not on the other. I've already moved to [kubernetes/ingress-nginx](https://github.com/kubernetes/ingress-nginx/) which describes my exact use case [here](https://kubernetes.github.io/ingress-nginx/deploy/baremetal/#via-the-host-network), so unfortunately I can no longer access the logs to give more complete feedback.
