### ISSUE TITLE
Image registry credentials should be configured form private registries protected with credentials.

### ISSUE THREAD

**Issue by frjaraur** [nginxinc/nginx-ingress-operator#43]
**Is your feature request related to a problem? Please describe.**
Image registry credentials should be configured form private registries protected with credentials. Deployments and other resources use secrets for managing required credentials. 

**Describe the solution you'd like**
We will need to be able to configure a secret to use for image registry.

**Describe alternatives you've considered**
In this case the only way is to change current Deployment and redeploy Pods.

**Comment by TuxInvader** [comment]
Any news on the ability to use Pull Secrets?

**Comment by subodh-hatkar** [comment]
In my project, we are in similar situation where we need to pull nginx-ingress image from our own private registry by using something like `imagePullSecrets` which is supported  in `Deployment` kind K8s resources but not in this `NginxIngressController` kind! Any idea when such feature will be added?

**Comment by lucacome** [comment]
This project has moved to https://github.com/nginxinc/nginx-ingress-helm-operator
If this is still an issue, please report it again in that repo.
Thanks!
