### ISSUE TITLE
Ingress operator creates a default TLS secret with type Opaque

### ISSUE THREAD

**Issue by danvarelajar** [nginxinc/nginx-ingress-operator#44]
Ingress operator creates a default TLS secret with type Opaque. When you create the ingress controller without default secret one must be created. Operator creates the secret but type is opaque:
NAME                    TYPE     DATA   AGE
my-ingress-controller   Opaque   2      10m

Ingress controller fails to start as it requires a secrete with type kubernetes.io/tls:

F0203 10:47:21.792100       1 main.go:427] Error trying to get the default server TLS secret my-nginx-ingress/my-ingress-controller: my-nginx-ingress/my-ingress-controller is invalid: TLS Secret must be of the type kubernetes.io/tls

**To Reproduce**
1. Deploy ingress controller and wit for the error.
2. kubectl get logs from ingress controller pod.
3. See error

**Expected behavior**
Ingress controller is deployed with a default certificate and key generated by the operator.

**Your environment**
* Version of the NGINX Ingress Operator: 0.0.7
* Version of the Ingress Controller: 1.10.0
* Version of Kubernetes: 1.19.6
* Kubernetes platform: Azure
* Using NGINX or NGINX Plus: Plus

**Comment by Dean-Coakley** [comment]
HI @danvarelajar 

NGINX Ingress Operator `0.0.7` only supports KIC 1.9.x. (See version matrix: https://github.com/nginxinc/nginx-ingress-operator#nginx-ingress-operator)

A new version of the operator will be released shortly with support for KIC 1.10.

**Comment by danvarelajar** [comment]
Thanks Dean. I assumed 0.0.7 supported 1.10.1. Workaround is easy though.
Cheers
