### ISSUE TITLE
Documentation: enableCRDs is required

### ISSUE THREAD

**Issue by rgordill** [nginxinc/nginx-ingress-operator#68]
**Describe the bug**
According with the doc (https://github.com/nginxinc/nginx-ingress-operator/blob/master/docs/nginx-ingress-controller.md), spec.enableCRDs is not required, but the CRD definition says it is.

**To Reproduce**
1. Use the example in the doc with only the required fields
2. Get the error "The NginxIngressController "my-nginx-ingress-controller" is invalid: spec.enableCRDs: Required value"

**Expected behavior**
Update docs to clarify that required field

**Your environment**
* Version of the NGINX Ingress Operator - master

**Comment by Dean-Coakley** [comment]
Thanks for opening this issue @rgordill .

I will make `enableCRDs` optional to be consistent with the behaviour of the NGINX Ingress Controller and it's helm chart.
