### ISSUE TITLE
nginx operator pod getting CRD error after updated to the new version

### ISSUE THREAD

**Issue by kcokyaman** [nginxinc/nginx-ingress-operator#78]
**Is your feature request related to a problem? Please describe.**
When operator updated to new version there is a following error in operator pod. 
{"level":"error","ts":1615446496.9901729,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"NginxIngressController.k8s.nginx.org","error":"no matches for kind \"NginxIngressController\" in version \"k8s.nginx.org/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\tsigs.k8s.io/controller-runtime@v0.6.3/pkg/source/source.go:117\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\tsigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:143\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\tsigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:184\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\tsigs.k8s.io/controller-runtime@v0.6.3/pkg/manager/internal.go:661"}

**Describe the solution you'd like**
We need to be able update from OperatorHub

**Describe alternatives you've considered**
I used a workaroud that manually delete all nginx crds and reinstalled operator.

**Comment by pleshakov** [comment]
Hi @kcokyaman 

Could you possibly share the steps you went through when upgrading the operator? This would help us reproduce the problem.

**Comment by itfabrik** [comment]
same here

Openshift 4.6, Subscribed to:
alpha nginx-ingress-operator.v0.1.0 Update Channel

nginx-ingress-operator pod currently in crash loop

{"level":"error","ts":1615501247.179404,"logger":"cmd","msg":"","error":"error creating KIC CRDs: error updating CustomResourceDefinition policies.k8s.nginx.org: CustomResourceDefinition.apiextensions.k8s.io \"policies.k8s.nginx.org\" is invalid: status.storedVersions[0]: Invalid value: \"v1alpha1\": must appear in spec.versions","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\tgithub.com/nginxinc/nginx-ingress-operator/cmd/manager/main.go:143\nruntime.main\n\truntime/proc.go:225"}

**Comment by pleshakov** [comment]
Hi @itfabrik 

in your case,  could try to delete `kubectl delete crd policies.k8s.nginx.org`?
Please also see `Upgrade Instructions` section here https://github.com/nginxinc/nginx-ingress-operator/releases/tag/v0.1.0

**Comment by itfabrik** [comment]
thanks , that worked, did not see those update instructions

**Comment by kcokyaman** [comment]
> Hi @kcokyaman
> 
> Could you possibly share the steps you went through when upgrading the operator? This would help us reproduce the problem.

Hello @pleshakov ,
I am using nginx operator on the Openshift 4.6. Openshift automatically updated the nginx operator and the issue happened. I realized that it is explained on the release notes after I checked this page. But I think It 's still problem when the operator set automated update.

**Comment by jakuboskera** [comment]
same here, I've just did a fresh installation (no any previous installations of operator in k8s cluster) and the pod was stuck in CrashLoopBackOff, after `kubectl delete crd policies.k8s.nginx.org`, the pod is working fine. I followed your installation instructions from  https://github.com/nginxinc/nginx-ingress-operator/blob/master/docs/manual-installation.md.

**Comment by alekonko** [comment]
Same problem on many ocp 4.6 clusters. 
The deletion of crd policies.k8s.nginx.org fix issue.

**Comment by pleshakov** [comment]
> Same problem on many ocp 4.6 clusters.
The deletion of crd policies.k8s.nginx.org fix issue.

Hi @alekonko 
Did you also have the auto upgrade of the Operator enabled?

**Comment by alekonko** [comment]
Yes, we have a couple of ocp clusters with nginx ingress operator installed for test purpose (with Cis integration).

We forgot to put operator in manual update.

Bye

**Comment by ciarams87** [comment]
Closing this issue as it relates version 0.1.0 of the Operator. Resolution is detailed in the Upgrade Instructions here https://github.com/nginxinc/nginx-ingress-operator/releases/tag/v0.1.0. 

Please note that the nginx-ingress-operator currently supports basic install only - see details on the [Operator Capability Levels here](https://sdk.operatorframework.io/docs/advanced-topics/operator-capabilities/operator-capabilities/)

Kind regards,
Ciara
