### ISSUE TITLE
Object aliases are already widely used in Openshift / ACM.

### ISSUE THREAD

**Issue by thekoma** [nginxinc/nginx-ingress-operator#84]
**Describe the bug**
Kubernetes resources and aliases are always different by the domain. 
Same name resources are common and we often forget about it.
But in this case Nginx is using a resource that is already used in ACM driven environment.
That can lead to tedious cases.

**To Reproduce**
Install Open Cluster Manager (Red Hat Advanced Cluster Manager) and Nginx Ingress Controller Operator
Try to get a policy (There goes the problem which one?)

```bash
oc api-resources|egrep  '^NAME| plc | pol '
NAME                                  SHORTNAMES         APIGROUP                                       NAMESPACED   KIND
policies                              plc                policy.open-cluster-management.io              true         Policy
policies                              pol                k8s.nginx.org                                                 true         Policy

```

**Workaround**
You can either use the FQDN or the shortname

```
plc or policies.policy.open-cluster-management.io
pol or policies.k8s.nginx.org
```

**Solution**
No solution there apart changing the names
I won't get on who did it first. 
But at least we have a trace in the issues.

**Comment by thekoma** [comment]
By reference: https://github.com/open-cluster-management/multicluster-observability-operator/issues/421

**Comment by pleshakov** [comment]
Hi @thekoma 

How big is this problem in your opinion? What's the impact?

**Comment by thekoma** [comment]
> Hi @thekoma
> 
> How big is this problem in your opinion? What's the impact?

The problem is on the end user usability.
When the user want to list the policy it has to know that the object is policy.k8s.nginx.org  
so all the instruction in the documentation should refer to the FQDN:
`oc get policy.k8s.nginx.org` 
 same per ACM:
`oc get policy.policy.open-cluster-management.io`  (even more cacophonic . )

The real problem is "knowing this".
