### ISSUE TITLE
Improved Documentation

### ISSUE THREAD

**Issue by ssc327** [nginxinc/nginx-ingress-operator#9]
I am trying to get more information about this operator's capabilities but I am struggling to do so. Specifically I would like to understand the following:

1. Why is this operator not visible on operatorhub.io?

1. What is the maturity of the operator? Can it do seamless upgrades?

**Comment by Rulox** [comment]
Hi @ssc327 

The main reason of the operator was to help Openshift users to have a RedHat certified way of installing the Kubernetes Ingress Controller. That's why the operator is only available inside the Openshift console in the RH Certified Operatorhub.

However, we're planning to add visibility in the vanilla Kubernetes community as well, I'm going to keep this issue opened to track this process (eventually that might include to publish the operator in operatorhub.io)

About the seamless updates, the operator is able to update the Ingress Controller seamlessly, yes.

**Comment by ssc327** [comment]
Thank you for the details. I recall that operatorhub has different capability levels, would you happen to know which level is this operator? 
Do you know if there are plans or a roadmap to get the operator to the highest capability level? 


![Screenshot_20200619-080724](https://user-images.githubusercontent.com/39785421/85131021-044d2780-b204-11ea-875b-1040edbbf275.jpg)

**Comment by Rulox** [comment]
Up to Level II for now. For upgrades (Level II), what we support right now is:
`Operand can be upgraded as part of changing the CR`. So changing the version of the `NginxIngressController` image tag, should update the Ingress Controller with no problem (unless we specify there are more changes required).

The idea is to keep adding capabilities in the future yes, I'm afraid I can't share a roadmap right now. Also, some levels (for example Full Lifecycle) do not apply 100% with a type of application like the Ingress Controller. For instance, backup (stateless), cluster (there's no really cluster of Ingress Controllers), etc... But we can add things like: liveness/readiness probes, pod limits, etc). 

We're always happy to get feedback from the community. What are you really trying to solve with this operator? (Apart from install/upgrades). Real life use cases can help us to identify and prepare future work.

Thanks

**Comment by ssc327** [comment]
Thank you for your prompt responses. At the moment I am exploring options for setting up an ingress controller on my cluster. The two primary options I have come across are using the operator or helm. At this time using the operator on a vanilla k8s cluster looks to be more work that just using helm but I was wondering if over time the operator would become richer and if investing time using it now would be worthwhile.

In terms of specific problems, I do not have any right now however I do worry about the added burden of needing to keep my Nginx controller up-to-date and I was wondering if an operator could someday provide automatic upgrades.
